### ISSUE TITLE
Adding a hyphen breaks autocomplete

### ISSUE THREAD

**Issue by believer** [yaegassy/coc-tailwindcss3#17]
When I start typing, I get autocomplete suggestions. Here I'm going to add a padding, `px`:

<img width="494" alt="Screenshot 2022-10-06 at 14 32 01" src="https://user-images.githubusercontent.com/1478102/194313894-7d9bd531-ffc7-4087-987f-70184e6193e9.png">

But, when I add hyphen (-) the `px` styles disappear:

<img width="409" alt="Screenshot 2022-10-06 at 14 32 07" src="https://user-images.githubusercontent.com/1478102/194314012-80bc0c76-c6e6-48d7-959c-8e25f1c744ce.png">

The current example is in Vue, but I've also got the same behavior in React.

**Comment by yaegassy** [comment]
This feature seemed to be causing problems. Please update `coc-tailwindcss3` as we have removed the problematic feature. `:CocUpdate`

- <https://github.com/yaegassy/coc-tailwindcss3/pull/12>

**Comment by BhasherBEL** [comment]
Hi, this issue is marked as solved but I'm still experiencing the problem with the version 0.5.7. In my case, when I add `-`, nothing is shown.

![image](https://github.com/yaegassy/coc-tailwindcss3/assets/45831883/928590b0-35f8-4ade-bf40-b4a6eef671ba)
![image](https://github.com/yaegassy/coc-tailwindcss3/assets/45831883/5a6753ed-06c0-4d9a-badb-4c3ea335d810)
