### ISSUE TITLE
Headwind runOnSave not working with "coc.preferences.formatOnSaveFiletypes"

### ISSUE THREAD

**Issue by stephenafamo** [yaegassy/coc-tailwindcss3#32]
`tailwindCSS.headwind.runOnSave` does not work if `formatOnSave` is turned on.

```json
{
    "coc.preferences.formatOnSaveFiletypes": ["*"],
    "tailwindCSS.headwind.runOnSave": true
}
```

Is there a way to get them both working together?

**Comment by yaegassy** [comment]
In the current coc.nvim, only one system of formatters is running.

Therefore, if you have, for example, `coc-pretteir` or `coc-html` installed, this format feature on the `coc-tailwindcss3` side is not working because that formatting function is prioritized and executed.

It is recommended to run the `tailwindCSS.headwind.sortTailwindClasses` command manually or install `coc-prettier` and use the `prettier-plugin-tailwindcss`.

- `:CocCommand tailwindCSS.headwind.sortTailwindClasses`
- <https://github.com/tailwindlabs/prettier-plugin-tailwindcss>
